name: build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'features/yt-dl-fix'
  
env:
  platforms: linux/amd64
   #,linux/arm64,linux/arm/v7

jobs:
  docker:
    name: master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.platforms }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          # arm/v6,7,8: https://github.com/alpinelinux/docker-alpine/issues/135
          # Alpine 3.13.0+ requires: libseccomp 2.4.2 _and_ docker engine v19.04+
          # https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements
          platforms: ${{ env.platforms }}
          push: true
          build-args: |
            VERSION=master
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/snapserver:latest
